src/java/py/com/palermo/curriculoadm/entities/EstadoCivil.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.palermo.curriculoadm.entities;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import py.com.palermo.curriculoadm.generico.Auditable;

/**
 *
 * @author christian.romero
 */
@Entity
public class EstadoCivil implements Serializable , Auditable{

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String nombre;
    @Enumerated(EnumType.STRING)
    private Estado estado;

    public EstadoCivil() {
        estado = Estado.ACTIVO;
    }
    
    

    public Estado getEstado() {
        return estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof EstadoCivil)) {
            return false;
        }
        EstadoCivil other = (EstadoCivil) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return nombre;
    }

}

src/java/py/com/palermo/curriculoadm/web/CurriculoBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.palermo.curriculoadm.web;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.ejb.EJB;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;

import javax.inject.Named;
import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormat;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import py.com.palermo.curriculoadm.entities.Area;
import py.com.palermo.curriculoadm.entities.Ciudad;
import py.com.palermo.curriculoadm.entities.Curriculo;
import py.com.palermo.curriculoadm.entities.EstadoCurriculo;
import py.com.palermo.curriculoadm.entities.Estudio;
import py.com.palermo.curriculoadm.entities.Experiencia;
import py.com.palermo.curriculoadm.entities.ExperienciaLaboral;
import py.com.palermo.curriculoadm.entities.Localidad;
import py.com.palermo.curriculoadm.entities.ReferenciaLaboral;
import py.com.palermo.curriculoadm.entities.ReferenciaPersonal;
import py.com.palermo.curriculoadm.generico.AbstractDAO;
import py.com.palermo.curriculoadm.generico.BeanGenerico;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.IAreaDAO;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.ICiudadDAO;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.ICurriculoDAO;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.IEmpresaDAO;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.IEstudioDAO;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.IExperienciaDAO;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.ILocalidadDAO;

/**
 *
 * @author christian
 */
@Named
@ViewScoped
public class CurriculoBean extends BeanGenerico<Curriculo> implements Serializable {

    @EJB
    private ICurriculoDAO ejb;
    @EJB
    private IAreaDAO areaDAO;
    @EJB
    private IExperienciaDAO experienciaDAO;
    @EJB
    private IEstudioDAO estudioDAO;
    @EJB
    private IEmpresaDAO empresaDAO;
    
    @EJB
    private ICiudadDAO ciudadDAO;
    
    @EJB
    private ILocalidadDAO localidadDAO;

    private UploadedFile file;

    @Override
    public Curriculo getActual() {
        Curriculo R = super.getActual();
        if (R.getId() == null || R.getId() == 0) {

            if (R.getReferenciasLaborales() == null) {
                List<ReferenciaLaboral> refsLaboral = new ArrayList<>();
                ReferenciaLaboral rl1 = new ReferenciaLaboral();
                rl1.setIndice(1);
                rl1.setCurriculo(R);
                ReferenciaLaboral rl2 = new ReferenciaLaboral();
                rl2.setCurriculo(R);
                rl2.setIndice(2);

                refsLaboral.add(rl1);
                refsLaboral.add(rl2);
                R.setReferenciasLaborales(refsLaboral);
            }

            if (R.getReferenciasPersonales() == null) {
                List<ReferenciaPersonal> refsPersonales = new ArrayList<>();

                ReferenciaPersonal rp1 = new ReferenciaPersonal();
                ReferenciaPersonal rp2 = new ReferenciaPersonal();
                rp1.setCurriculo(R);
                rp2.setCurriculo(R);
                rp1.setIndice(1);
                rp2.setIndice(2);

                refsPersonales.add(rp1);
                refsPersonales.add(rp2);

                R.setReferenciasPersonales(refsPersonales);
            }

            if (R.getExperienciasLaborales() == null) {
                List<ExperienciaLaboral> expsLaborales = new ArrayList<>();
                ExperienciaLaboral exp1 = new ExperienciaLaboral();
                ExperienciaLaboral exp2 = new ExperienciaLaboral();
                exp1.setIndice(1);
                exp2.setIndice(2);
                exp1.setCurriculo(R);
                exp2.setCurriculo(R);

                expsLaborales.add(exp1);
                expsLaborales.add(exp2);

                R.setExperienciasLaborales(expsLaborales);
            }
        }

        return R;
    }

    @Override
    public AbstractDAO<Curriculo> getEjb() {
        return ejb;
    }

    @Override
    public Curriculo getNuevo() {
        return new Curriculo();
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public SelectItem[] getSelectItemsAreas() {

        List<Area> listaAreas;
        if (getActual().getEmpresa() == null) {
            listaAreas = areaDAO.findAllSinEmpresa();

        } else if (empresaDAO.tieneArea(getActual().getEmpresa())) {
            listaAreas = areaDAO.findAllConEmpresa(getActual().getEmpresa());
        } else {
            listaAreas = areaDAO.findAllSinEmpresa();
        }

        SelectItem[] items = new SelectItem[listaAreas.size() + 1];
        int i = 0;
        items[0] = new SelectItem("", "Todas las areas");
        i++;
        for (Area a : listaAreas) {
            items[i++] = new SelectItem(a, a.toString());
        }

        return items;
    }

    
    
    public SelectItem[] getSelectItemsCiudades() {

        List<Ciudad> listaCiudades;
        if(getActual() != null && getActual().getDepartamento() != null){
            listaCiudades = ciudadDAO.findAllActivePorDepartamento(getActual().getDepartamento());
        }else {
            listaCiudades = new ArrayList<>();
        }
        
        
        SelectItem[] items = new SelectItem[listaCiudades.size() + 1];
        int i = 0;
        items[0] = new SelectItem("", "Ninguna");
        i++;
        for (Ciudad c : listaCiudades) {
            items[i++] = new SelectItem(c, c.toString());
        }

        return items;
    }
    
    
    public SelectItem[] getSelectItemsLocalidades() {

        List<Localidad> listaLocalidades;
        if(getActual() != null && getActual().getDepartamento() != null){
            listaLocalidades = localidadDAO.findAllActivePorDepartamento(getActual().getDepartamento());
        }else {
            listaLocalidades = new ArrayList<>();
        }
        
        
        SelectItem[] items = new SelectItem[listaLocalidades.size() + 1];
        int i = 0;
        items[0] = new SelectItem("", "Ninguna");
        i++;
        for (Localidad l : listaLocalidades) {
            items[i++] = new SelectItem(l, l.toString());
        }

        return items;
    }
    
    public SelectItem[] getSelectItemsExperiencias() {

        List<Experiencia> listaExperiencias;
        if (getActual().getEmpresa() == null) {
            listaExperiencias = experienciaDAO.findAllSinEmpresa();

        } else if (empresaDAO.tieneExperiencia(getActual().getEmpresa())) {
            listaExperiencias = experienciaDAO.findAllConEmpresa(getActual().getEmpresa());
        } else {
            listaExperiencias = experienciaDAO.findAllSinEmpresa();
        }

        SelectItem[] items = new SelectItem[listaExperiencias.size() + 1];
        int i = 0;
        items[0] = new SelectItem("", "Ninguna");
        i++;
        for (Experiencia e : listaExperiencias) {
            items[i++] = new SelectItem(e, e.toString());
        }

        return items;
    }

    public SelectItem[] getSelectItemsEstudios() {

        List<Estudio> listaEstudios;
        if (getActual().getEmpresa() == null) {
            listaEstudios = estudioDAO.findAllSinEmpresa();

        } else if (empresaDAO.tieneEstudio(getActual().getEmpresa())) {
            listaEstudios = estudioDAO.findAllConEmpresa(getActual().getEmpresa());
        } else {
            listaEstudios = estudioDAO.findAllSinEmpresa();
        }

        SelectItem[] items = new SelectItem[listaEstudios.size() + 1];
        int i = 0;
        items[0] = new SelectItem("", "Niguno");
        i++;
        for (Estudio e : listaEstudios) {
            items[i++] = new SelectItem(e, e.toString());
        }

        return items;
    }

    public SelectItem[] getSelectItemsDias() {
        SelectItem[] items = new SelectItem[32];
        items[0] = new SelectItem("", "--");
        for (int i = 1; i < 32; i++) {
            items[i] = new SelectItem("" + i, "" + i);
        }
        return items;
    }

    public SelectItem[] getSelectItemsAnios() {
        SelectItem[] items = new SelectItem[41];
        items[0] = new SelectItem("", "--");
        for (int i = 1; i < 41; i++) {
            items[i] = new SelectItem("" + (i + 1959), "" + (i + 1959));
        }
        return items;
    }

    public SelectItem[] getSelectItemsMes() {
        SelectItem[] items = new SelectItem[13];
        items[0] = new SelectItem("", "--");
        items[1] = new SelectItem("01", "Enero");
        items[2] = new SelectItem("02", "Febrero");
        items[3] = new SelectItem("03", "Marzo");
        items[4] = new SelectItem("04", "Abril");
        items[5] = new SelectItem("05", "Mayo");
        items[6] = new SelectItem("06", "Junio");
        items[7] = new SelectItem("07", "Julio");
        items[8] = new SelectItem("08", "Agosto");
        items[9] = new SelectItem("09", "Septiembre");
        items[10] = new SelectItem("10", "Octubre");
        items[11] = new SelectItem("11", "Noviembre");
        items[12] = new SelectItem("12", "Diciembre");

        return items;
    }

    public void handleFileUpload(FileUploadEvent event) throws IOException {
        if (event.getFile() != null) {

            file = event.getFile();
            getActual().setAdjunto(file.getFileName());
            System.out.println("FILE: " + file);
        }
    }

    public void copyFile() {
        try {

            System.out.println("FILE en COPY: " + file);
            FacesContext fc = FacesContext.getCurrentInstance();

src/java/py/com/palermo/curriculoadm/web/EstadoCivilBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.palermo.curriculoadm.web;


import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import py.com.palermo.curriculoadm.entities.EstadoCivil;
import py.com.palermo.curriculoadm.generico.AbstractDAO;
import py.com.palermo.curriculoadm.generico.BeanGenerico;
import py.com.palermo.curriculoadm.sesionbeans.interfaces.IEstadoCivilDAO;



/**
 *
 * @author christian
 */
@Named
@ViewScoped
public class EstadoCivilBean extends BeanGenerico<EstadoCivil> implements Serializable{

    @EJB private IEstadoCivilDAO ejb;
    
    
    @Override
    public AbstractDAO<EstadoCivil> getEjb() {
        return ejb;
    }

    @Override
    public EstadoCivil getNuevo() {
        return new EstadoCivil();
    }

    
}

web/admin/estadoCivil/cuerpo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core">



    <div class="Container100 Responsive100" >
        <div class="ContainerIndent">
            <div class="Card ShadowEffect HeiAutoOnMobile">
                <h2 class="CardTopic"><i class="fa fa-plus-square Fs25 Fleft MarRight10 "></i>#{titulo}</h2>
                <div class="Separator"/>
                <h:form>

                    <p:growl autoUpdate="true" id="mensajes"/>

                    <p:outputPanel id="panel">
                        <h:panelGrid columns="3" columnClasses="gridColumn1,gridColumn2,gridColumn2" >
                            <p:outputLabel value="Descripción" for="nombre" />
                            <h:outputText value="#{estadoCivilBean.actual.nombre}" rendered="#{(contexto == 'vista')}"/>
                            <p:inputText value="#{estadoCivilBean.actual.nombre}" required="true" id="nombre" rendered="#{not(contexto == 'vista')}"/>
                            <p:message for="nombre"/>

                            <p:outputLabel value="Estado" for="estado" />
                            <p:selectOneMenu value="#{estadoCivilBean.actual.estado}" id="estado" rendered="#{(contexto == 'edicion')}">
                                <f:selectItems value="#{productorEnums.obtEstados()}"/>
                            </p:selectOneMenu>
                            <h:outputText value="#{estadoCivilBean.actual.estado}" rendered="#{(contexto == 'vista')}"/>
                            <p:message for="estado" rendered="#{not(contexto == 'edicion')}"/>
                        </h:panelGrid>  
                    </p:outputPanel>

                    <br/>


                    <p:commandButton value="Crear" action="#{estadoCivilBean.create()}" styleClass="Fleft GreenButton" update="panel" rendered="#{(contexto == 'creacion')}"/>
                    <p:commandButton value="Guardar" action="#{estadoCivilBean.edit()}" styleClass="Fleft BlueButton" update="panel" rendered="#{(contexto == 'edicion')}"/>
                    <p:commandButton value="Eliminar" action="#{estadoCivilBean.remove()}" styleClass="Fleft RedButton" update="panel" rendered="#{(contexto == 'vista')}"/>

                    <p:button value="Editar"  styleClass="Fleft BlueButton" outcome="edita" rendered="#{(contexto == 'vista')}">
                        <f:param name="id" value="#{estadoCivilBean.actual.id}"/>
                    </p:button>
                    <p:button value="Atras"  styleClass="Fleft PurpleButton" outcome="listado"/>
                    <br/>

                </h:form>

            </div>
        </div>
    </div>
</ui:composition>

web/admin/estadoCivil/edita.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core">
    <ui:define name="content">

        <f:metadata>
            <f:viewParam name="id" value="#{estadoCivilBean.id}"/>
            <f:viewAction action="#{estadoCivilBean.cargaDatos()}"/>
        </f:metadata>

        <ui:include src="cuerpo.xhtml">
            <ui:param name="contexto" value="edicion"/>
            <ui:param name="titulo" value="EDICIÓN DE EMPRESA"/>
        </ui:include>

    </ui:define>
</ui:composition>

web/admin/estadoCivil/listado.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="content">

        <h:form id="formList">
            <div class="Container100 Responsive100">
                <div class="ContainerIndent">
                    <div class="Card ShadowEffect HeiAutoOnMobile">
                        <h2 class="CardTopic"><i class="icon-google132 Fs20 Fleft MarRight10"></i>LISTADO DE ESTADO CIVIL
                            <p:button id="createButton" value="Nuevo" outcome="nuevo" styleClass="GreenButton Fright"/>
                            <p:button id="viewButton"   value="Ver" outcome="vista" disabled="#{empty estadoCivilBean.actual.id}" styleClass="Button Fright">
                                <f:param name="id" value="#{estadoCivilBean.actual.id}"/>
                            </p:button>
                        </h2>
                        <div class="Separator"/>


                        <p:dataTable value="#{estadoCivilBean.findAll()}" var="e" paginator="true" rows="20" paginatorPosition="bottom" reflow="true"
                                     selection="#{estadoCivilBean.actual}"
                                     rowKey="#{e.id}"
                                     selectionMode="single">

                            <p:ajax event="rowSelect"   update=":formList:createButton :formList:viewButton"/>
                            <p:ajax event="rowUnselect" update=":formList:createButton :formList:viewButton"/>

                           

                            <p:column headerText="Nombre">
                                <h:outputText value="#{e.nombre}"/>
                            </p:column>
                            <p:column headerText="Estado">
                                <h:outputText value="#{e.estado}"/>
                            </p:column>
                        </p:dataTable>

                    </div>
                </div>
            </div>
        </h:form>


    </ui:define>
</ui:composition>

web/admin/estadoCivil/nuevo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="content">
        <ui:include src="cuerpo.xhtml">
            <ui:param name="contexto" value="creacion"/>
            <ui:param name="titulo" value="CREACIÓN DE ESTADO CIVIL"/>
        </ui:include>

    </ui:define>
</ui:composition>

web/admin/estadoCivil/vista.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="content">
        <f:metadata>
            <f:viewParam name="id" value="#{estadoCivilBean.id}"/>
            <f:viewAction action="#{estadoCivilBean.cargaDatos()}"/>
        </f:metadata>

        <ui:include src="cuerpo.xhtml">
            <ui:param name="contexto" value="vista"/>
            <ui:param name="titulo" value="VISTA DE ESTADO CIVIL"/>
        </ui:include>

    </ui:define>


</ui:composition>